name: localenvironment-action

on:
  push:
#    tags:
#      - 'ddns/v*'
#      - 'acme/v*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, freebsd, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Detect service from tag
        id: detect
        run: |
          TAG_REF=${GITHUB_REF##*/}
          if [[ $TAG_REF == ddns/* ]]; then
            echo "service=ddns" >> $GITHUB_OUTPUT
          elif [[ $TAG_REF == acme/* ]]; then
            echo "service=acme" >> $GITHUB_OUTPUT
          else
            echo "service=unknown" >> $GITHUB_OUTPUT

      - name: Build binary for selected platform
        if: steps.detect.outputs.service != 'unknown'
        run: |
          SERVICE=${{ steps.detect.outputs.service }}
          OUTPUT="${SERVICE}_${{ matrix.goos }}_${{ matrix.goarch }}"
          cd cmd/$SERVICE
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ../../$OUTPUT .

      - name: Upload Release Asset
        if: steps.detect.outputs.service != 'unknown'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.detect.outputs.service }}_${{ matrix.goos }}_${{ matrix.goarch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}